apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.mysql.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
