apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.mysql.replicaCount }}
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: {{ .Values.mysql.resources.requests.cpu }}
            memory: {{ .Values.mysql.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mysql.resources.limits.cpu }}
            memory: {{ .Values.mysql.resources.limits.memory }}
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      tolerations:
      - key: {{ .Values.mysql.tolerations.key | quote }}
        operator: {{ .Values.mysql.tolerations.operator | quote }}
        value: {{ .Values.mysql.tolerations.value | quote }}
        effect: {{ .Values.mysql.tolerations.effect | quote }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ .Values.mysql.affinity.podAntiAffinity.key | quote }}
                operator: {{ .Values.mysql.affinity.podAntiAffinity.operator }}
                values:
                - {{ .Values.mysql.affinity.podAntiAffinity.value }}
            topologyKey: {{ .Values.mysql.affinity.podAntiAffinity.topologyKey | quote }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.mysql.affinity.nodeAffinity.key | quote }}
                operator: {{ .Values.mysql.affinity.nodeAffinity.operator }}
                values:
                - {{ .Values.mysql.affinity.nodeAffinity.value }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mysql.pvc.requests.storage }}
